<?php
//上传文件
//获取上传的文件
print_r($_POST);
echo("<br>");
print_r($_FILES);
//获取上传文件对应的字典
$fileInfo=$_FILES["uploadFile"];
$fileName=$fileInfo["name"];
$filePath=$fileInfo["tmp_name"];
echo("<br>");
echo($fileName);
echo("<br>");
echo("$filePath");

//移动文件
move_uploaded_file($filePath,"./source/".$fileName);//旧的路径，新的路径
//上传到这里的source文件夹
?>